### ISSUE TITLE
manifest files should not be space-delimited 

### ISSUE THREAD

**Issue by jasoncpatton** [HTPhenotyping/htcondor_file_transfer#2]
If filenames (or paths, when #1 is addressed) contain spaces, the current space-delimited manifest file will not be parsed correctly. Instead of imposing a restriction on users to not use spaces, use something less common (tab?) to delimit fields in the manifest file.

**Comment by jasoncpatton** [comment]
This is actually ok for now, changing tag to enhancement. Would be nice to make them all JSON(-ish).

**Comment by JoshKarpel** [comment]
Resolved by #10  (except for metadata files, which is coming down the pipe)
